-- Esquema MVP de Cronopios / Diseño Multimedial.
-- Ejecutar en Supabase SQL Editor. Todas las tablas usan UUID del usuario autenticado.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  degree text not null default 'Diseño Multimedial',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  code text unique,
  year smallint not null check (year between 1 and 5),
  semester smallint check (semester between 1 and 2),
  created_at timestamptz not null default now()
);
alter table public.subjects add column if not exists curriculum text not null default 'old';
alter table public.profiles add column if not exists curriculum text not null default 'old';

create table if not exists public.correlatives (
  subject_id bigint not null references public.subjects(id) on delete cascade,
  required_subject_id bigint not null references public.subjects(id) on delete cascade,
  primary key (subject_id, required_subject_id),
  check (subject_id <> required_subject_id)
);

-- Compatibilidad con tablas existentes. El tipo de las claves debe coincidir
-- exactamente con subjects.id (algunas instalaciones previas usaban uuid).
do $$
declare
  subject_id_type text;
  correlatives_subject_type text;
  correlatives_required_type text;
begin
  select format_type(a.atttypid, a.atttypmod)
    into subject_id_type
    from pg_attribute a
    where a.attrelid = 'public.subjects'::regclass
      and a.attname = 'id'
      and not a.attisdropped;

  if subject_id_type = 'uuid' then
    select format_type(a.atttypid, a.atttypmod)
      into correlatives_subject_type
      from pg_attribute a
      where a.attrelid = 'public.correlatives'::regclass
        and a.attname = 'subject_id'
        and not a.attisdropped;
    select format_type(a.atttypid, a.atttypmod)
      into correlatives_required_type
      from pg_attribute a
      where a.attrelid = 'public.correlatives'::regclass
        and a.attname = 'required_subject_id'
        and not a.attisdropped;

    if correlatives_subject_type is null or correlatives_required_type is null then
      alter table public.correlatives add column if not exists subject_id uuid;
      alter table public.correlatives add column if not exists required_subject_id uuid;
    elsif correlatives_subject_type <> 'uuid' or correlatives_required_type <> 'uuid' then
      raise exception 'public.correlatives usa tipos incompatibles (% y %), mientras subjects.id usa uuid. Respaldá y migrá esas filas antes de continuar.',
        correlatives_subject_type, correlatives_required_type;
    end if;

    if not exists (
      select 1 from pg_constraint
      where conname = 'correlatives_subject_id_fkey'
        and conrelid = 'public.correlatives'::regclass
    ) then
      alter table public.correlatives
        add constraint correlatives_subject_id_fkey
        foreign key (subject_id) references public.subjects(id) on delete cascade;
    end if;
    if not exists (
      select 1 from pg_constraint
      where conname = 'correlatives_required_subject_id_fkey'
        and conrelid = 'public.correlatives'::regclass
    ) then
      alter table public.correlatives
        add constraint correlatives_required_subject_id_fkey
        foreign key (required_subject_id) references public.subjects(id) on delete cascade;
    end if;
  elsif subject_id_type in ('bigint', 'integer') then
    alter table public.correlatives add column if not exists subject_id bigint;
    alter table public.correlatives add column if not exists required_subject_id bigint;
    if not exists (
      select 1 from pg_constraint
      where conname = 'correlatives_subject_id_fkey'
        and conrelid = 'public.correlatives'::regclass
    ) then
      alter table public.correlatives
        add constraint correlatives_subject_id_fkey
        foreign key (subject_id) references public.subjects(id) on delete cascade;
    end if;
    if not exists (
      select 1 from pg_constraint
      where conname = 'correlatives_required_subject_id_fkey'
        and conrelid = 'public.correlatives'::regclass
    ) then
      alter table public.correlatives
        add constraint correlatives_required_subject_id_fkey
        foreign key (required_subject_id) references public.subjects(id) on delete cascade;
    end if;
  end if;
end $$;

create table if not exists public.user_subjects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'regular', 'passed')),
  grade numeric(3,1) check (grade between 1 and 10),
  passed_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, subject_id)
);

-- Compatibilidad con user_subjects de una instalación anterior.
-- La aplicación actual utiliza estos nombres para guardar estado, nota y fecha.
alter table public.user_subjects add column if not exists status text default 'pending';
alter table public.user_subjects add column if not exists grade numeric(3,1);
alter table public.user_subjects add column if not exists passed_at date;
alter table public.user_subjects add column if not exists created_at timestamptz not null default now();
alter table public.user_subjects add column if not exists updated_at timestamptz not null default now();

-- Normaliza el CHECK de status de instalaciones anteriores. La app utiliza
-- exclusivamente pending, regular y passed.
do $$
declare
  constraint_record record;
begin
  update public.user_subjects
  set status = case lower(status::text)
    when 'pendiente' then 'pending'
    when 'aprobada' then 'passed'
    when 'aprobado' then 'passed'
    when 'regularizada' then 'regular'
    when 'in_progress' then 'regular'
    when 'completed' then 'passed'
    else status
  end
  where status is not null;

  for constraint_record in
    select conname
    from pg_constraint
    where conrelid = 'public.user_subjects'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%status%'
  loop
    execute format('alter table public.user_subjects drop constraint if exists %I', constraint_record.conname);
  end loop;

  alter table public.user_subjects
    add constraint user_subjects_status_check
    check (status in ('pending', 'regular', 'passed'));
end $$;

create table if not exists public.community_posts (
  id bigint generated by default as identity primary key,
  author_id uuid references auth.users(id) on delete set null,
  title text not null,
  body text not null,
  event_type text not null default 'aviso',
  event_date date,
  accent text not null default 'lime' check (accent in ('lime', 'fuchsia', 'cyan')),
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

-- Compatibilidad con una tabla community_posts creada por una versión anterior.
-- CREATE TABLE IF NOT EXISTS no modifica columnas de tablas existentes.
alter table public.community_posts add column if not exists author_id uuid references auth.users(id) on delete set null;
alter table public.community_posts add column if not exists title text;
alter table public.community_posts add column if not exists body text;
alter table public.community_posts add column if not exists event_type text default 'aviso';
alter table public.community_posts add column if not exists event_date date;
alter table public.community_posts add column if not exists accent text default 'lime';
alter table public.community_posts add column if not exists is_published boolean not null default true;
alter table public.community_posts add column if not exists created_at timestamptz not null default now();

-- Permite volver a ejecutar este archivo sin errores de políticas duplicadas.
drop policy if exists "Users can read their profile" on public.profiles;
drop policy if exists "Users can update their profile" on public.profiles;
drop policy if exists "Public can read subjects" on public.subjects;
drop policy if exists "Public can read correlatives" on public.correlatives;
drop policy if exists "Users manage their subject history" on public.user_subjects;
drop policy if exists "Authenticated users read published posts" on public.community_posts;

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.correlatives enable row level security;
alter table public.user_subjects enable row level security;
alter table public.community_posts enable row level security;

create policy "Users can read their profile" on public.profiles for select to authenticated using (auth.uid() = id);
create policy "Users can update their profile" on public.profiles for update to authenticated using (auth.uid() = id);
create policy "Public can read subjects" on public.subjects for select to authenticated using (true);
create policy "Public can read correlatives" on public.correlatives for select to authenticated using (true);
create policy "Users manage their subject history" on public.user_subjects for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Authenticated users read published posts" on public.community_posts for select to authenticated using (is_published = true);

create or replace function public.handle_new_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'nombre', 'Estudiante'));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_profile on auth.users;
create trigger on_auth_user_created_profile
  after insert on auth.users
  for each row execute procedure public.handle_new_profile();

-- Plan oficial publicado por la Facultad de Artes:
-- https://fba.unlp.edu.ar/licenciatura-en-diseno-multimedial/
-- y PDF enlazado por la Facultad:
-- https://fba.unlp.edu.ar/wp-content/uploads//2020/10/Plan-con-logo.pdf
--
-- Los códigos DM-* son identificadores internos de Cronopios, no códigos oficiales
-- de la Facultad. Los espacios "a elección" se modelan como materias del plan
-- para que el estudiante pueda registrar su cumplimiento.
insert into public.subjects (name, code, year, semester) values
  ('Taller de diseño multimedial I', 'DM-1-TALLER', 1, 1),
  ('Lenguaje multimedial I', 'DM-1-LENGUAJE', 1, 1),
  ('Tecnología multimedial I', 'DM-1-TECNOLOGIA', 1, 2),
  ('Historia social general', 'DM-1-HISTORIA', 1, 2),
  ('Producción de textos B', 'DM-1-TEXTOS', 1, 2),
  ('Arte contemporáneo', 'DM-1-ARTE', 1, 2),
  ('Taller de diseño multimedial II', 'DM-2-TALLER', 2, 1),
  ('Lenguaje multimedial II', 'DM-2-LENGUAJE', 2, 1),
  ('Tecnología multimedial II', 'DM-2-TECNOLOGIA', 2, 2),
  ('Identidad, estado y sociedad en Argentina y Latinoamérica', 'DM-2-IDENTIDAD', 2, 2),
  ('Taller de diseño multimedial III', 'DM-3-TALLER', 3, 1),
  ('Lenguaje multimedial III', 'DM-3-LENGUAJE', 3, 1),
  ('Tecnología multimedial III', 'DM-3-TECNOLOGIA', 3, 2),
  ('Estética', 'DM-3-ESTETICA', 3, 2),
  ('Taller de diseño multimedial IV', 'DM-4-TALLER', 4, 1),
  ('Lenguaje multimedial IV', 'DM-4-LENGUAJE', 4, 1),
  ('Tecnología multimedial IV', 'DM-4-TECNOLOGIA', 4, 1),
  ('Gestión de proyectos', 'DM-4-GESTION', 4, 1),
  ('Teoría de la práctica artística', 'DM-4-TEORIA', 4, 2),
  ('Epistemología de las artes', 'DM-4-EPISTEMOLOGIA', 4, 2),
  ('Metodología de la investigación', 'DM-4-METODOLOGIA', 4, 2),
  ('Seminario de formación general a elección', 'DM-4-SEMINARIO-GENERAL', 4, 2),
  ('Taller de diseño multimedial V', 'DM-5-TALLER', 5, 1),
  ('Seminario de formación especifica a elección I', 'DM-5-SEMINARIO-1', 5, 2),
  ('Seminario de formación especifica a elección II', 'DM-5-SEMINARIO-2', 5, 2)
on conflict (code) do update set
  name = excluded.name,
  year = excluded.year,
  semester = excluded.semester;

-- Correlatividades completas del plan.
insert into public.correlatives (subject_id, required_subject_id)
select required_subject.id, prerequisite_subject.id
from (values
  ('DM-2-TALLER', 'DM-1-TALLER'),
  ('DM-2-LENGUAJE', 'DM-1-LENGUAJE'),
  ('DM-2-TECNOLOGIA', 'DM-1-TECNOLOGIA'),
  ('DM-2-IDENTIDAD', 'DM-1-HISTORIA'),
  ('DM-2-IDENTIDAD', 'DM-1-ARTE'),
  ('DM-3-TALLER', 'DM-2-TALLER'),
  ('DM-3-LENGUAJE', 'DM-2-LENGUAJE'),
  ('DM-3-TECNOLOGIA', 'DM-2-TECNOLOGIA'),
  ('DM-3-ESTETICA', 'DM-2-IDENTIDAD'),
  ('DM-3-ESTETICA', 'DM-1-ARTE'),
  ('DM-4-TALLER', 'DM-3-TALLER'),
  ('DM-4-LENGUAJE', 'DM-3-LENGUAJE'),
  ('DM-4-TECNOLOGIA', 'DM-3-TECNOLOGIA'),
  ('DM-4-GESTION', 'DM-4-TALLER'),
  ('DM-4-GESTION', 'DM-4-TECNOLOGIA'),
  ('DM-4-TEORIA', 'DM-3-ESTETICA'),
  ('DM-4-EPISTEMOLOGIA', 'DM-3-ESTETICA'),
  ('DM-4-METODOLOGIA', 'DM-1-HISTORIA'),
  ('DM-4-METODOLOGIA', 'DM-1-TEXTOS'),
  ('DM-4-SEMINARIO-GENERAL', 'DM-3-ESTETICA'),
  ('DM-5-TALLER', 'DM-4-TALLER'),
  ('DM-5-TALLER', 'DM-4-GESTION'),
  ('DM-5-SEMINARIO-1', 'DM-4-EPISTEMOLOGIA'),
  ('DM-5-SEMINARIO-1', 'DM-4-METODOLOGIA'),
  ('DM-5-SEMINARIO-2', 'DM-5-SEMINARIO-1')
) as prerequisites(subject_code, prerequisite_code)
join public.subjects required_subject on required_subject.code = prerequisites.subject_code
join public.subjects prerequisite_subject on prerequisite_subject.code = prerequisites.prerequisite_code
on conflict do nothing;
