create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  carrera text,
  promedio numeric(4,2),
  created_at timestamptz not null default now()
);

create table public.materias_carrera (
  id bigint generated by default as identity primary key,
  carrera text not null,
  nombre text not null,
  anio integer,
  tipo text default 'obligatoria'
);

create table public.materias_usuario (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  materia_id bigint not null references public.materias_carrera(id) on delete cascade,
  estado text not null default 'pendiente' check (estado in ('pendiente', 'regular', 'aprobada')),
  nota numeric(3,1) check (nota between 1 and 10),
  fecha_aprobacion date,
  created_at timestamptz not null default now(),
  unique(usuario_id, materia_id)
);

alter table public.perfiles enable row level security;
alter table public.materias_carrera enable row level security;
alter table public.materias_usuario enable row level security;

create policy "Cada estudiante ve su perfil" on public.perfiles for select using (auth.uid() = id);
create policy "Cada estudiante actualiza su perfil" on public.perfiles for update using (auth.uid() = id);
create policy "Cada estudiante crea su perfil" on public.perfiles for insert with check (auth.uid() = id);
create policy "Plan de estudios público" on public.materias_carrera for select using (true);
create policy "Cada estudiante administra sus materias" on public.materias_usuario for all using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.perfiles (id, nombre) values (new.id, coalesce(new.raw_user_meta_data->>'nombre', 'Estudiante'));
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.materias_carrera (carrera, nombre, anio) values
('Artes Audiovisuales', 'Historia del arte I', 1),
('Artes Audiovisuales', 'Taller de producción', 1),
('Artes Audiovisuales', 'Estética', 2),
('Artes Audiovisuales', 'Lenguaje audiovisual', 2);
