create table if not exists public.user_schedule_selections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_schedule_id bigint not null references public.course_schedules(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (user_id, course_schedule_id)
);

create index if not exists user_schedule_selections_user_idx on public.user_schedule_selections(user_id);
alter table public.user_schedule_selections enable row level security;

drop policy if exists "Users read own schedule selections" on public.user_schedule_selections;
create policy "Users read own schedule selections" on public.user_schedule_selections
  for select to authenticated using (user_id = auth.uid());
drop policy if exists "Users insert own schedule selections" on public.user_schedule_selections;
create policy "Users insert own schedule selections" on public.user_schedule_selections
  for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Users delete own schedule selections" on public.user_schedule_selections;
create policy "Users delete own schedule selections" on public.user_schedule_selections
  for delete to authenticated using (user_id = auth.uid());

grant select, insert, delete on public.user_schedule_selections to authenticated;
grant usage, select on sequence public.user_schedule_selections_id_seq to authenticated;
revoke all on public.user_schedule_selections from anon;
