create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_success_at timestamptz,
  failure_count integer not null default 0,
  disabled_at timestamptz
);

create table if not exists public.event_reminders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  academic_event_id bigint not null references public.academic_events(id) on delete cascade,
  reminder_type text not null check (reminder_type in ('registration_open','registration_closing_24h','registration_last_day','event_start')),
  scheduled_for timestamptz not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, academic_event_id, reminder_type)
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  reminder_id bigint not null references public.event_reminders(id) on delete cascade,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  scheduled_for timestamptz not null,
  attempted_at timestamptz,
  status text not null default 'pending' check (status in ('pending','sent','failed','expired')),
  error_code text,
  created_at timestamptz not null default now(),
  unique (reminder_id, subscription_id)
);

create index if not exists event_reminders_due_idx on public.event_reminders (scheduled_for) where enabled = true;
create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id) where disabled_at is null;

alter table public.push_subscriptions enable row level security;
alter table public.event_reminders enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists "Users manage own push subscriptions" on public.push_subscriptions;
create policy "Users manage own push subscriptions" on public.push_subscriptions for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage own event reminders" on public.event_reminders;
create policy "Users manage own event reminders" on public.event_reminders for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Deliveries are private operational records. They are only accessed by the service role.
