create table if not exists public.user_custom_schedule_slots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id text not null,
  subject_name text not null,
  academic_year smallint not null,
  semester smallint not null check (semester between 1 and 2),
  weekday text check (weekday in ('Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes')),
  start_time time,
  end_time time,
  classroom text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, subject_id, academic_year, semester),
  check ((start_time is null and end_time is null) or (start_time is not null and end_time is not null and end_time > start_time))
);

create index if not exists user_custom_schedule_slots_user_idx on public.user_custom_schedule_slots(user_id);
alter table public.user_custom_schedule_slots enable row level security;
create policy "Users read own custom schedules" on public.user_custom_schedule_slots for select to authenticated using (user_id = auth.uid());
create policy "Users add own custom schedules" on public.user_custom_schedule_slots for insert to authenticated with check (user_id = auth.uid());
create policy "Users edit own custom schedules" on public.user_custom_schedule_slots for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Users remove own custom schedules" on public.user_custom_schedule_slots for delete to authenticated using (user_id = auth.uid());
grant select, insert, update, delete on public.user_custom_schedule_slots to authenticated;
grant usage, select on sequence public.user_custom_schedule_slots_id_seq to authenticated;
revoke all on public.user_custom_schedule_slots from anon;
