-- Horarios personales y aliases verificados. No altera ni elimina horarios publicados.
alter table public.user_custom_schedule_slots
  add column if not exists notes text;

alter table public.user_custom_schedule_slots
  drop constraint if exists user_custom_schedule_slots_notes_length;
alter table public.user_custom_schedule_slots
  add constraint user_custom_schedule_slots_notes_length
  check (notes is null or length(notes) <= 2000);

create table if not exists public.subject_aliases (
  id bigint generated by default as identity primary key,
  subject_id text not null,
  alias text not null check (length(btrim(alias)) between 1 and 160),
  curriculum text not null,
  verified boolean not null default false,
  source text,
  created_at timestamptz not null default now()
);

create index if not exists subject_aliases_curriculum_idx
  on public.subject_aliases(curriculum) where verified = true;
create unique index if not exists subject_aliases_unique_idx
  on public.subject_aliases(curriculum, subject_id, lower(alias));

alter table public.subject_aliases enable row level security;
drop policy if exists "Read verified subject aliases" on public.subject_aliases;
create policy "Read verified subject aliases" on public.subject_aliases
  for select to authenticated using (verified = true);
grant select on public.subject_aliases to authenticated;
revoke all on public.subject_aliases from anon;
