-- Horarios institucionales descontinuados: conservar tablas antiguas sin depender de ellas.
create table if not exists public.user_course_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id text,
  subject_name text not null,
  academic_year smallint not null,
  semester smallint check (semester between 1 and 2),
  weekday text check (weekday in ('Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes')),
  start_time time,
  end_time time,
  classroom text,
  location text,
  commission text,
  notes text check (notes is null or length(notes) <= 2000),
  legacy_custom_slot_id bigint unique,
  legacy_selection_id bigint unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Las filas históricas pueden tener horas incompletas; el API valida filas nuevas.
  check (end_time is null or start_time is null or end_time > start_time)
);

create index if not exists user_course_entries_user_period_idx
  on public.user_course_entries(user_id, academic_year, semester);
alter table public.user_course_entries enable row level security;
drop policy if exists "Users read own course entries" on public.user_course_entries;
create policy "Users read own course entries" on public.user_course_entries for select to authenticated using (user_id = auth.uid());
drop policy if exists "Users add own course entries" on public.user_course_entries;
create policy "Users add own course entries" on public.user_course_entries for insert to authenticated with check (user_id = auth.uid());
drop policy if exists "Users edit own course entries" on public.user_course_entries;
create policy "Users edit own course entries" on public.user_course_entries for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists "Users remove own course entries" on public.user_course_entries;
create policy "Users remove own course entries" on public.user_course_entries for delete to authenticated using (user_id = auth.uid());
grant select, insert, update, delete on public.user_course_entries to authenticated;
grant usage, select on sequence public.user_course_entries_id_seq to authenticated;
revoke all on public.user_course_entries from anon;

-- Copiar primero los horarios ya personalizados, sin mantener la FK a course_schedules.
insert into public.user_course_entries
  (user_id, subject_id, subject_name, academic_year, semester, weekday, start_time, end_time,
   classroom, location, commission, notes, legacy_custom_slot_id, created_at, updated_at)
select user_id, subject_id, subject_name, academic_year, semester, weekday, start_time, end_time,
       classroom, location, commission, notes, id, created_at, updated_at
from public.user_custom_schedule_slots
on conflict (legacy_custom_slot_id) do nothing;

-- Las selecciones anteriores se congelan como datos personales. Si ya existe una copia
-- personalizada de la misma fuente, no se duplica el encuentro.
insert into public.user_course_entries
  (user_id, subject_id, subject_name, academic_year, semester, weekday, start_time, end_time,
   classroom, location, commission, legacy_selection_id, created_at, updated_at)
select sel.user_id, schedule.subject_id, schedule.raw_subject_name, schedule.academic_year,
       schedule.semester, schedule.weekday, schedule.start_time, schedule.end_time,
       schedule.classroom, schedule.campus, schedule.commission, sel.id, sel.created_at, sel.created_at
from public.user_schedule_selections sel
join public.course_schedules schedule on schedule.id = sel.course_schedule_id
where not exists (
  select 1 from public.user_custom_schedule_slots custom
  where custom.user_id = sel.user_id and custom.source_schedule_id = sel.course_schedule_id
)
on conflict (legacy_selection_id) do nothing;

-- Durante el despliegue, la versión anterior puede seguir escribiendo en la tabla
-- personal vieja. Sincronizar esas escrituras hasta que todos los clientes cambien.
create or replace function public.sync_legacy_custom_course_entry()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    delete from public.user_course_entries where legacy_custom_slot_id = old.id;
    return old;
  end if;
  insert into public.user_course_entries
    (user_id, subject_id, subject_name, academic_year, semester, weekday, start_time, end_time,
     classroom, location, commission, notes, legacy_custom_slot_id, created_at, updated_at)
  values
    (new.user_id, new.subject_id, new.subject_name, new.academic_year, new.semester,
     new.weekday, new.start_time, new.end_time, new.classroom, new.location,
     new.commission, new.notes, new.id, new.created_at, new.updated_at)
  on conflict (legacy_custom_slot_id) do update set
    subject_id = excluded.subject_id, subject_name = excluded.subject_name,
    academic_year = excluded.academic_year, semester = excluded.semester,
    weekday = excluded.weekday, start_time = excluded.start_time, end_time = excluded.end_time,
    classroom = excluded.classroom, location = excluded.location,
    commission = excluded.commission, notes = excluded.notes, updated_at = excluded.updated_at;
  if new.source_schedule_id is not null then
    delete from public.user_course_entries entry
    using public.user_schedule_selections selection
    where entry.legacy_selection_id = selection.id
      and selection.user_id = new.user_id
      and selection.course_schedule_id = new.source_schedule_id;
  end if;
  return new;
end $$;
drop trigger if exists sync_legacy_custom_course_entry on public.user_custom_schedule_slots;
create trigger sync_legacy_custom_course_entry
  after insert or update or delete on public.user_custom_schedule_slots
  for each row execute function public.sync_legacy_custom_course_entry();

-- Una versión anterior también puede agregar o quitar selecciones durante el
-- despliegue. Congelarlas como entradas personales sin mantener un enlace nuevo.
create or replace function public.sync_legacy_schedule_selection()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    delete from public.user_course_entries where legacy_selection_id = old.id;
    return old;
  end if;
  if exists (
    select 1 from public.user_custom_schedule_slots custom
    where custom.user_id = new.user_id and custom.source_schedule_id = new.course_schedule_id
  ) then return new; end if;
  insert into public.user_course_entries
    (user_id, subject_id, subject_name, academic_year, semester, weekday, start_time, end_time,
     classroom, location, commission, legacy_selection_id, created_at, updated_at)
  select new.user_id, schedule.subject_id, schedule.raw_subject_name,
         schedule.academic_year, schedule.semester, schedule.weekday,
         schedule.start_time, schedule.end_time, schedule.classroom,
         schedule.campus, schedule.commission, new.id, new.created_at, new.created_at
  from public.course_schedules schedule where schedule.id = new.course_schedule_id
  on conflict (legacy_selection_id) do nothing;
  return new;
end $$;
drop trigger if exists sync_legacy_schedule_selection on public.user_schedule_selections;
create trigger sync_legacy_schedule_selection
  after insert or delete on public.user_schedule_selections
  for each row execute function public.sync_legacy_schedule_selection();

comment on table public.course_schedules is
  'DEPRECATED: archivo historico de horarios institucionales. Ninguna experiencia activa de Mesita debe consultarlo.';
comment on table public.user_schedule_selections is
  'DEPRECATED: selecciones historicas migradas a user_course_entries; no crear filas nuevas.';
