create table if not exists public.data_sources (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  source_type text not null check (source_type in ('academic_calendar', 'course_schedule', 'schedule_fallback')),
  index_url text not null,
  current_resource_url text,
  parser_key text not null,
  is_enabled boolean not null default true,
  last_checked_at timestamptz,
  last_success_at timestamptz,
  last_checksum text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.import_runs (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.data_sources(id) on delete cascade,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running', 'success', 'warning', 'failed')),
  checksum text,
  records_found integer not null default 0,
  records_changed integer not null default 0,
  warning_count integer not null default 0,
  error_summary text,
  created_at timestamptz not null default now()
);

create table if not exists public.academic_events (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.data_sources(id) on delete cascade,
  external_key text not null,
  title text not null,
  event_type text not null check (event_type in ('course_registration', 'final_registration', 'final_exam_period', 'semester_start', 'semester_end', 'academic_break', 'other')),
  registration_start date,
  registration_end date,
  starts_at date,
  ends_at date,
  academic_year smallint not null,
  semester smallint check (semester between 1 and 2),
  degree text,
  curriculum text,
  source_url text not null,
  source_label text not null,
  source_updated_at timestamptz,
  status text not null default 'draft' check (status in ('draft', 'verified', 'published', 'stale')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, external_key)
);

create table if not exists public.course_schedules (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.data_sources(id) on delete cascade,
  external_key text not null,
  -- Instalaciones históricas pueden tener subjects.id como bigint o uuid.
  -- Se conserva el vínculo opcional como texto para que esta migración sea
  -- compatible sin alterar subjects ni imponer una FK de tipo incompatible.
  subject_id text,
  raw_subject_name text not null,
  curriculum text,
  academic_year smallint not null,
  semester smallint check (semester between 1 and 2),
  course_year smallint,
  commission text,
  weekday text not null,
  start_time time not null,
  end_time time,
  campus text,
  classroom text,
  notes text,
  source_url text not null,
  source_label text not null,
  status text not null default 'draft' check (status in ('draft', 'verified', 'published', 'stale')),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_id, external_key)
);

insert into public.data_sources (key, name, source_type, index_url, current_resource_url, parser_key)
values
  ('multimedia-schedules-new-second', 'Departamento de Multimedia — materias plan nuevo, segundo cuatrimestre', 'course_schedule', 'https://www2.fba.unlp.edu.ar/multimedia/estudiantes/horarios/', 'https://docs.google.com/spreadsheets/d/1BtPLVDtHHm_l48K5ScrwAGbVCdOlXKUm/export?format=csv', 'google-sheet-grid'),
  ('multimedia-schedules-new-first', 'Departamento de Multimedia — materias plan nuevo, primer cuatrimestre', 'course_schedule', 'https://www2.fba.unlp.edu.ar/multimedia/estudiantes/horarios/', 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSP4x4_y4dhi0yoS4KTEAeze-52o4L7p5tNaaQ9IOSL2KOAL6FiN-Lc4A714nH79A/pub?output=csv', 'google-sheet-grid'),
  ('multimedia-schedules-old', 'Departamento de Multimedia — materias plan viejo', 'course_schedule', 'https://www2.fba.unlp.edu.ar/multimedia/estudiantes/horarios/', 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR5cgkziEGhGoaTOr0TPstNPaanxrqwBp1hWPmy2gSaSL9Fhu1H_B5RTwjlkVsahA/pub?output=csv', 'google-sheet-grid'),
  ('academic-calendar-2026-second', 'Secretaría Académica FDA — calendario académico 2026, segundo cuatrimestre', 'academic_calendar', 'https://www2.fba.unlp.edu.ar/academica/calendario-academico-2024-3/', 'https://drive.google.com/uc?export=download&id=105utASN95iq9MHRGf7k6rTRt4WppiC5P', 'academic-calendar-pdf'),
  ('academic-calendar-2026-first', 'Secretaría Académica FDA — calendario académico 2026, primer cuatrimestre', 'academic_calendar', 'https://www2.fba.unlp.edu.ar/academica/calendario-academico-2024-3/', 'https://drive.google.com/uc?export=download&id=19GB-uxVmWScSEpZwvE8cDTWGgyG6wAbG', 'academic-calendar-pdf'),
  ('sae-schedules', 'Secretaría de Asuntos Estudiantiles — horarios y aulas', 'schedule_fallback', 'https://www2.fba.unlp.edu.ar/sae/horarios-y-aulas/', 'https://www2.fba.unlp.edu.ar/sae/horarios-y-aulas/', 'sae-schedules')
on conflict (key) do update set current_resource_url = excluded.current_resource_url, updated_at = now();

alter table public.data_sources enable row level security;
alter table public.import_runs enable row level security;
alter table public.academic_events enable row level security;
alter table public.course_schedules enable row level security;

drop policy if exists "Public can read enabled sources" on public.data_sources;
create policy "Public can read enabled sources" on public.data_sources for select using (is_enabled = true);
drop policy if exists "Public can read published academic events" on public.academic_events;
create policy "Public can read published academic events" on public.academic_events for select using (status = 'published');
drop policy if exists "Public can read published course schedules" on public.course_schedules;
create policy "Public can read published course schedules" on public.course_schedules for select using (status = 'published');
